# -*- coding: utf-8 -*-
"""RQuickStart.R

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESrRS3OL23eyK3ZRAlaNDotyKr4bIBeW

# EDA
"""

data = iris
head(data)

"""glimpse"""

glimpse(data)

"""get data summary"""

summary(data)

"""unique values"""

unique(data$Species)

"""null values"""

sapply(data, anyNA)

colSums(is.na(data))